spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecomarket
    password: 1234567
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
